import { expect, test } from "@playwright/test";
import film from "../data/monsoon_film.json";

for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
  test(`Pacific evidence explorer at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport);
    await page.goto("/monsoon/");
    const explorer = page.locator("section").filter({ hasText: "Pacific evidence explorer" });
    await explorer.scrollIntoViewIfNeeded();
    await expect(explorer.locator(".pacField.on")).toHaveCount(1);
    await expect(explorer.locator(".pacPin")).toContainText("Andhra Pradesh");
    await explorer.getByRole("button", { name: "Earth imagery", exact: true }).click();
    await expect(explorer.locator(".pacField.on")).toHaveCSS("opacity", "0");
    await explorer.getByRole("button", { name: "Temperature anomaly", exact: true }).click();
    await expect(explorer.locator(".pacField.on")).toHaveCSS("opacity", "1");
    await explorer.getByRole("button", { name: "Previous month", exact: true }).click();
    const before = await explorer.locator(".pacMonth").innerText();
    await explorer.getByRole("slider", { name: "Month", exact: true }).fill("0");
    await expect(explorer.locator(".pacMonth")).not.toHaveText(before);
    await expect(explorer.getByRole("button", { name: "Previous month", exact: true })).toBeDisabled();
    await explorer.getByRole("button", { name: "Play through the months", exact: true }).click();
    await expect.poll(() => explorer.getByRole("slider", { name: "Month", exact: true }).inputValue()).not.toBe("0");
    await explorer.getByRole("button", { name: "Pause months", exact: true }).click();
    await explorer.getByRole("group", { name: "Monthly Niño 3.4 anomalies" }).getByRole("button").last().click();
    await expect(explorer.getByRole("button", { name: "Next month", exact: true })).toBeDisabled();
    await expect(explorer.getByText(/not wind measurements/)).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await explorer.screenshot({ path: testInfo.outputPath(`pacific-${viewport.width}.png`) });
    await explorer.locator(".pacStage").evaluate(element => element.scrollIntoView({ block: "center" }));
    await page.screenshot({ path: testInfo.outputPath(`pacific-viewport-${viewport.width}.png`) });
    await explorer.locator("summary").click();
    await expect(explorer.getByText(/NOAA Extended Reconstructed SST/)).toBeVisible();
  });

  test(`monsoon film plays and seeks at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/monsoon/", { waitUntil: "domcontentloaded" });
    const section = page.getByRole("region", { name: "From the Pacific to Andhra Pradesh" });
    await section.scrollIntoViewIfNeeded();
    const video = section.locator("video");
    await expect(video).toBeVisible();
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
    expect(await video.evaluate((v: HTMLVideoElement) => v.duration)).toBeCloseTo(film.duration, 1);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBe(viewport.width < 760 ? 1080 : 1920);
    if (viewport.width < 760) await section.getByRole("combobox", { name: "Film chapter" }).selectOption("2");
    else await section.getByRole("button", { name: /El Niño/ }).click();
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(film.chapters[2].start + .8);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.seeking)).toBe(false);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.paused)).toBe(false);
    await video.evaluate((v: HTMLVideoElement) => v.pause());
    if (viewport.width < 760) await expect(section.getByRole("combobox", { name: "Film chapter" })).toHaveValue("2");
    else await expect(section.getByRole("button", { name: /El Niño/ })).toHaveAttribute("aria-current", "step");
    await expect(section.getByRole("link", { name: "Download film" })).toHaveAttribute("href", /landscape\.mp4$/);
    await expect(section.getByRole("link", { name: "Vertical / WhatsApp" })).toHaveAttribute("href", /portrait\.mp4$/);
    const captionUrl = await video.locator("track").getAttribute("src");
    const captions = await page.request.get(captionUrl!);
    expect(captions.ok()).toBe(true);
    expect(await captions.text()).toContain("WEBVTT");
    await section.locator("summary").click();
    await expect(section.getByRole("link", { name: "NOAA ERSST v5" })).toBeVisible();
    await expect(section.getByRole("link", { name: "NIDM: drought preparedness and water conservation" })).toBeVisible();
    await expect(section.getByRole("link", { name: "MoHUA: AMRUT 2.0 urban water security" })).toBeVisible();
    await section.locator("summary").click();
    const preparation = film.chapters.findIndex(chapter => chapter.id === "prepare");
    if (viewport.width < 760) await section.getByRole("combobox", { name: "Film chapter" }).selectOption(String(preparation));
    else await section.getByRole("button", { name: /Preparedness/ }).click();
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(film.chapters[preparation].start + .8);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.seeking)).toBe(false);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.paused)).toBe(false);
    await video.evaluate((v: HTMLVideoElement) => v.pause());
    const bounds = await section.boundingBox();
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width + 1);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    expect(overflow).toBe(false);
    await section.screenshot({ path: testInfo.outputPath(`film-${viewport.width}.png`) });
    await video.evaluate(element => element.scrollIntoView({ block: "center" }));
    await page.screenshot({ path: testInfo.outputPath(`viewport-${viewport.width}.png`) });
    const city = film.chapters.findIndex(chapter => chapter.id === "cities");
    expect(city).toBe(preparation + 1);
    if (viewport.width < 760) await section.getByRole("combobox", { name: "Film chapter" }).selectOption(String(city));
    else await section.getByRole("button", { name: /Cities \/ reduce the impact/ }).click();
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(film.chapters[city].start + .8);
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.seeking)).toBe(false);
    await video.evaluate((v: HTMLVideoElement) => v.pause());
    await video.evaluate(element => element.scrollIntoView({ block: "center" }));
    await page.screenshot({ path: testInfo.outputPath(`city-viewport-${viewport.width}.png`) });
    expect(errors).toEqual([]);
  });
}
