"""Rebuild the Crystal 3D view's embedded dataset from MEASURED readings.

The view used to embed a one-off dataset: the model's in-sample fit per year plus
a straight-line "forecast" for the next two, generated by hand and never
refreshed. This rebuilds it from the active V2 observation series every week.

Each year's value is the pre-monsoon (May) reading, CGWB's own convention, so
every year compares like with like. A year with no May reading is interpolated
from the neighbouring years and flagged in `gap`, so the view can say so. There
is no forecast: nForecast is always 0.

Run from anywhere:  python phase3_levels/build_crystal_data.py
"""
import csv
import difflib
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
APP_DATA = os.path.join(ROOT, "app", "data")
HTML = os.path.join(ROOT, "app", "public", "water-crystal-3d.html")
EXTRACTION = os.path.join(HERE, "data", "mandal_extraction_cgwb2024.csv")

PRE_MONSOON_MONTH = "05"
# A year enters the timeline once at least this share of mandals has a May reading.
MIN_YEAR_COVERAGE = 0.5
# A mandal is shown only if at least this share of the timeline is measured,
# so interpolation never carries more of its line than the readings do.
MIN_MANDAL_COVERAGE = 0.5
POLY_POINTS = 24
GW_LINE = re.compile(r"^const GW = .*;$", re.M)


def load(name):
    with open(os.path.join(APP_DATA, name)) as handle:
        return json.load(handle)


def norm(value):
    text = re.sub(r"\(.*?\)", " ", str(value).upper())
    text = re.sub(r"\b(RURAL|URBAN|MANDAL)\b", " ", text)
    text = re.sub(r"[^A-Z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def boundary_ordinal(boundary_id):
    """'ap-prototype-boundary-<slug>-046' -> 46, the feature's 1-based position."""
    match = re.search(r"-(\d+)$", boundary_id or "")
    return int(match.group(1)) if match else 0


def simplify(ring, target=POLY_POINTS):
    if len(ring) <= target:
        return ring
    return [ring[int(i * len(ring) / target)] for i in range(target)]


def fill_gaps(values):
    """Linear interpolation between measured years, held flat past either end."""
    known = [i for i, v in enumerate(values) if v is not None]
    filled = list(values)
    for i, v in enumerate(values):
        if v is not None:
            continue
        before = [k for k in known if k < i]
        after = [k for k in known if k > i]
        if before and after:
            a, b = before[-1], after[0]
            filled[i] = values[a] + (values[b] - values[a]) * (i - a) / (b - a)
        else:
            filled[i] = values[before[-1] if before else after[0]]
    return filled


def ols_slope(points):
    """Least-squares slope in metres per year; positive means deepening."""
    n = len(points)
    mx = sum(x for x, _ in points) / n
    my = sum(y for _, y in points) / n
    sxx = sum((x - mx) ** 2 for x, _ in points)
    return sum((x - mx) * (y - my) for x, y in points) / sxx if sxx else 0.0


def load_extraction():
    """{district: {normalised mandal: (stage_pct, category)}} from CGWB 2024."""
    table = defaultdict(dict)
    with open(EXTRACTION, newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                stage = round(float(row["stage_pct"]), 1)
            except (TypeError, ValueError):
                continue
            table[norm(row["district"])][norm(row["mandal"])] = (stage, row["category"])
    return table


def match_extraction(table, district, mandal):
    """CGWB figure for a mandal, or None. Never guesses across districts.

    Tried in order: exact name in its own district; a close spelling in its own
    district; then an exact name elsewhere, but only when that name is unique in
    the state. The last step covers mandals moved into districts formed after
    the 2024 assessment (Polavaram, Markapuram) without letting a same-named
    mandal in another district lend its figure.
    """
    candidates = table.get(norm(district), {})
    key = norm(mandal)
    if key in candidates:
        return candidates[key]
    close = difflib.get_close_matches(key, list(candidates), n=1, cutoff=0.84)
    if close:
        return candidates[close[0]]
    elsewhere = [rows[key] for rows in table.values() if key in rows]
    return elsewhere[0] if len(elsewhere) == 1 else None


def build():
    records = load("mandal_groundwater_records_v2.json")["records"]
    series = load("mandal_observation_series_v2.json")["series"]
    manifest = load("dataset_manifest.json")
    # Joined by the boundary's ordinal, not its name: 16 district/mandal names
    # occur twice in the boundary file, and a name join would draw both
    # mandals on one polygon.
    geometry = load("ap_map_geometry.json")["mandals"]
    extraction = load_extraction()

    # May readings per mandal; a month reported twice is averaged.
    may = {}
    for mandal_id, entry in series.items():
        by_year = defaultdict(list)
        for obs in entry["observations"]:
            year, month = obs["period"][:4], obs["period"][5:7]
            if month == PRE_MONSOON_MONTH and obs.get("value") is not None:
                by_year[year].append(obs["value"])
        may[mandal_id] = {y: sum(v) / len(v) for y, v in by_year.items()}

    per_year = defaultdict(int)
    for readings in may.values():
        for year in readings:
            per_year[year] += 1
    eligible = sorted(y for y, n in per_year.items() if n >= MIN_YEAR_COVERAGE * len(series))
    if not eligible:
        sys.exit("No year has enough pre-monsoon readings to build the Crystal view.")
    years = [str(y) for y in range(int(eligible[0]), int(eligible[-1]) + 1)]

    out, dropped_sparse, dropped_geometry, stage_matched = [], 0, 0, 0
    for record in records:
        identity = record["identity"]
        readings = may.get(identity["mandalId"])
        if not readings:
            continue
        raw = [readings.get(y) for y in years]
        measured = [i for i, v in enumerate(raw) if v is not None]
        if len(measured) < MIN_MANDAL_COVERAGE * len(years):
            dropped_sparse += 1
            continue
        ordinal = boundary_ordinal(identity["boundaryId"])
        feature = geometry[ordinal - 1] if 0 < ordinal <= len(geometry) else None
        if not feature or not feature.get("rings"):
            dropped_geometry += 1
            continue
        ring = max(feature["rings"], key=len)
        filled = fill_gaps(raw)
        slope = ols_slope([(int(years[i]), raw[i]) for i in measured])
        stage = match_extraction(extraction, identity["districtName"], identity["mandalName"])
        stage_matched += stage is not None
        out.append({
            "b": ordinal,
            "n": identity["mandalName"].title(),
            "d": identity["districtName"].title(),
            "poly": [[round(p[0], 4), round(p[1], 4)] for p in simplify(ring)],
            "lvl": [round(v, 1) for v in filled],
            "gap": [i for i, v in enumerate(raw) if v is None],
            "trend": round(slope, 2),
            "stage": stage[0] if stage else None,
            "cat": stage[1] if stage else None,
        })

    lons = [p[0] for m in out for p in m["poly"]]
    lats = [p[1] for m in out for p in m["poly"]]
    dataset = {
        "bbox": [min(lons), min(lats), max(lons), max(lats)],
        "years": years,
        "nForecast": 0,
        "basis": "measured_pre_monsoon_may",
        "throughPeriod": manifest["periods"]["latestObservationPeriod"],
        "generatedAt": manifest["generatedAt"],
        "mandals": out,
    }
    stats = {
        "mandals": len(out),
        "years": f"{years[0]}-{years[-1]}",
        "interpolated_cells": sum(len(m["gap"]) for m in out),
        "dropped_sparse": dropped_sparse,
        "dropped_no_geometry": dropped_geometry,
        "cgwb_matched": stage_matched,
    }
    return dataset, stats


def main():
    dataset, stats = build()
    with open(HTML) as handle:
        html = handle.read()
    line = "const GW = " + json.dumps(dataset, separators=(",", ":")) + ";"
    updated, count = GW_LINE.subn(lambda _m: line, html)
    if count != 1:
        sys.exit(f"Expected exactly one `const GW = ...;` line in {HTML}, found {count}.")
    with open(HTML, "w") as handle:
        handle.write(updated)
    print(
        f"crystal: {stats['mandals']} mandals, {stats['years']} pre-monsoon (May), "
        f"{stats['interpolated_cells']} interpolated mandal-years, "
        f"{stats['cgwb_matched']} CGWB-matched"
    )
    print(
        f"  dropped: {stats['dropped_sparse']} too sparse, "
        f"{stats['dropped_no_geometry']} without a boundary polygon"
    )


if __name__ == "__main__":
    main()
